[build]
  publish = "dist"
  command = "rm -rf dist && mkdir dist && cp -R index.html main.js modules particle_systems public textures README.txt dist/ && find dist -name '.DS_Store' -delete && find dist -name '._*' -delete"
